/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'unit-types': UnitType;
    units: Unit;
    facilities: Facility;
    media: Media;
    packages: Package;
    users: User;
    exports: Export;
    imports: Import;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'unit-types': UnitTypesSelect<false> | UnitTypesSelect<true>;
    units: UnitsSelect<false> | UnitsSelect<true>;
    facilities: FacilitiesSelect<false> | FacilitiesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    packages: PackagesSelect<false> | PackagesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    exports: ExportsSelect<false> | ExportsSelect<true>;
    imports: ImportsSelect<false> | ImportsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
    'site-settings': SiteSetting;
    labels: Label;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    labels: LabelsSelect<false> | LabelsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      createCollectionExport: TaskCreateCollectionExport;
      createCollectionImport: TaskCreateCollectionImport;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "unit-types".
 */
export interface UnitType {
  id: number;
  /**
   * Used in the page URL. Locked once saved (admins can still change it).
   */
  slug: string;
  /**
   * Stand-in content. Shows a "contoh" badge on the site while placeholder badges are on (Site settings → Developer).
   */
  placeholder?: boolean | null;
  /**
   * e.g. "Tipe 1"
   */
  name: string;
  /**
   * Small accent line, e.g. "Ruko Hook"
   */
  label?: string | null;
  /**
   * Homepage card. Shown at 6:5 on black with the building centred; at least 1000 px.
   */
  cardImage: number | Media;
  landArea: number;
  buildingArea: number;
  floors: number;
  bedrooms: number;
  bathrooms: number;
  /**
   * Top of the info panel on the type page.
   */
  intro: string;
  /**
   * Shown after the spec rows (land, building, floors, bedrooms, bathrooms), which come from the numbers above. E.g. "Daya listrik: 3.500 VA".
   */
  infoRows?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  sequence: number | Package;
  /**
   * In scroll order. The first is normally the facade, then each floor.
   */
  parts: {
    /**
     * e.g. "Fasad", "Lantai 1"
     */
    name: string;
    /**
     * In links, e.g. /tipe/tipe-1/#lantai-2
     */
    key: string;
    /**
     * Keyframe in the sequence (0-based).
     */
    frame: number;
    text: string;
    /**
     * Label of the floor plan (Floor plans tab) to show with this part, e.g. "Lantai 1".
     */
    floorPlan?: string | null;
    id?: string | null;
  }[];
  /**
   * Denah thumbnails in the panel; they open in the lightbox.
   */
  floorPlans?:
    | {
        /**
         * e.g. "Lantai 1", "Atap"
         */
        label: string;
        /**
         * Portrait plan. SVG, or PNG/JPG at least 1200 px.
         */
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Lightbox gallery, in order. At least 1600 px on the long side. Empty hides the Gallery button.
   */
  gallery?: (number | Media)[] | null;
  vr?: {
    /**
     * Published 3DVista tour (https://…) or a site path. Empty hides the VR button.
     */
    url?: string | null;
    mode?: ('embedded' | 'newTab') | null;
  };
  seo?: {
    /**
     * Browser tab title. Defaults to the type name.
     */
    title?: string | null;
    /**
     * Defaults to the sentence in Interface text → Type page → Default description.
     */
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describes the image for screen readers and search. For videos, a short title.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * Image sequences delivered as whole folders: scroll scenes (Kawasan, Cluster) and WebRotate 360 packages (type pages).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packages".
 */
export interface Package {
  id: number;
  name: string;
  kind: 'scene' | 'turntable';
  /**
   * Folder inside the site, e.g. /media/scroll/kawasan/ or /media/tipe-1/facade/
   */
  path: string;
  /**
   * Read from the package when available.
   */
  frames: number;
  /**
   * Frame width in px.
   */
  width?: number | null;
  /**
   * Frame height in px.
   */
  height?: number | null;
  /**
   * Tracked landmarks in manifest.json. Each hotspot follows one of these.
   */
  landmarks?: string[] | null;
  /**
   * Image shown before the viewer starts, e.g. /media/tipe-1/facade/images/facade_000.jpg
   */
  poster?: string | null;
  /**
   * Frame the viewer opens on.
   */
  firstImage?: number | null;
  /**
   * Frame the scroll scene starts on.
   */
  startFrame?: number | null;
  /**
   * Stand-in content. Shows a "contoh" badge on the site while placeholder badges are on (Site settings → Developer).
   */
  placeholder?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Status dots on the siteplan. Positions are % of the siteplan image, so re-check them if the siteplan changes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "units".
 */
export interface Unit {
  id: number;
  /**
   * e.g. A-01
   */
  unitId: string;
  status: 'available' | 'reserved' | 'sold';
  /**
   * Filled from the Unit ID if empty.
   */
  block?: string | null;
  /**
   * % of siteplan width
   */
  x: number;
  /**
   * % of siteplan height
   */
  y: number;
  /**
   * Not shown on the site yet.
   */
  type?: (number | null) | UnitType;
  /**
   * Internal only; never published.
   */
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "facilities".
 */
export interface Facility {
  id: number;
  /**
   * Caption under the image.
   */
  title: string;
  /**
   * Shown at 16:10. At least 1200 px wide.
   */
  image: number | Media;
  /**
   * Stand-in content. Shows a "contoh" badge on the site while placeholder badges are on (Site settings → Developer).
   */
  placeholder?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'editor' | 'sales';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports".
 */
export interface Export {
  id: number;
  name?: string | null;
  format: 'csv' | 'json';
  limit?: number | null;
  page?: number | null;
  sort?: string | null;
  sortOrder?: ('asc' | 'desc') | null;
  drafts?: ('yes' | 'no') | null;
  selectionToUse?: ('currentSelection' | 'currentFilters' | 'all') | null;
  fields?: string[] | null;
  collectionSlug: string;
  where?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports".
 */
export interface Import {
  id: number;
  collectionSlug: string;
  importMode?: ('create' | 'update' | 'upsert') | null;
  matchField?: string | null;
  status?: ('pending' | 'completed' | 'partial' | 'failed') | null;
  summary?: {
    imported?: number | null;
    updated?: number | null;
    total?: number | null;
    issues?: number | null;
    issueDetails?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'createCollectionExport' | 'createCollectionImport';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'createCollectionExport' | 'createCollectionImport') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'unit-types';
        value: number | UnitType;
      } | null)
    | ({
        relationTo: 'units';
        value: number | Unit;
      } | null)
    | ({
        relationTo: 'facilities';
        value: number | Facility;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'packages';
        value: number | Package;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "unit-types_select".
 */
export interface UnitTypesSelect<T extends boolean = true> {
  slug?: T;
  placeholder?: T;
  name?: T;
  label?: T;
  cardImage?: T;
  landArea?: T;
  buildingArea?: T;
  floors?: T;
  bedrooms?: T;
  bathrooms?: T;
  intro?: T;
  infoRows?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  sequence?: T;
  parts?:
    | T
    | {
        name?: T;
        key?: T;
        frame?: T;
        text?: T;
        floorPlan?: T;
        id?: T;
      };
  floorPlans?:
    | T
    | {
        label?: T;
        image?: T;
        id?: T;
      };
  gallery?: T;
  vr?:
    | T
    | {
        url?: T;
        mode?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "units_select".
 */
export interface UnitsSelect<T extends boolean = true> {
  unitId?: T;
  status?: T;
  block?: T;
  x?: T;
  y?: T;
  type?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "facilities_select".
 */
export interface FacilitiesSelect<T extends boolean = true> {
  title?: T;
  image?: T;
  placeholder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packages_select".
 */
export interface PackagesSelect<T extends boolean = true> {
  name?: T;
  kind?: T;
  path?: T;
  frames?: T;
  width?: T;
  height?: T;
  landmarks?: T;
  poster?: T;
  firstImage?: T;
  startFrame?: T;
  placeholder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports_select".
 */
export interface ExportsSelect<T extends boolean = true> {
  name?: T;
  format?: T;
  limit?: T;
  page?: T;
  sort?: T;
  sortOrder?: T;
  drafts?: T;
  selectionToUse?: T;
  fields?: T;
  collectionSlug?: T;
  where?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports_select".
 */
export interface ImportsSelect<T extends boolean = true> {
  collectionSlug?: T;
  importMode?: T;
  matchField?: T;
  status?: T;
  summary?:
    | T
    | {
        imported?: T;
        updated?: T;
        total?: T;
        issues?: T;
        issueDetails?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  hero: {
    eyebrow?: string | null;
    title: string;
    /**
     * Muted background loop. 1920×1080 H.264, ≤ 12 MB. Must be the same orbit as the Kawasan scene: the hero hands over to it on scroll.
     */
    loopVideo: number | Media;
    /**
     * Poster shown before the loop plays, 1920×1080.
     */
    cover: number | Media;
    /**
     * The film behind "Play Full Video", with controls. ≤ 60 MB.
     */
    fullVideo: number | Media;
    playLabel: string;
    /**
     * Small hint at the bottom.
     */
    scrollCue?: string | null;
  };
  kawasan: {
    title: string;
    intro: string;
    /**
     * The frame sequence scrubbed by scrolling.
     */
    scene: number | Package;
    /**
     * Button that leaves an open hotspot, e.g. "Kembali ke kawasan".
     */
    backLabel: string;
    /**
     * Markers on the scene. Opening one turns the orbit to its frame and zooms in.
     */
    hotspots?:
      | {
          /**
           * List item and location title.
           */
          title: string;
          /**
           * Marker label on the image. Defaults to the title.
           */
          shortLabel?: string | null;
          /**
           * Unique id, e.g. area-plaza.
           */
          key: string;
          /**
           * Shown while the location is open.
           */
          text: string;
          /**
           * Tracked landmark the marker follows (listed on the scene package).
           */
          landmark: string;
          /**
           * Orbit angle (frame) shown when opened. A new frame also needs a sharp detail frame (README).
           */
          defaultFrame: number;
          id?: string | null;
        }[]
      | null;
  };
  lokasi: {
    title: string;
    intro?: string | null;
    /**
     * Static area map, at least 1600 px wide. No interaction (brief).
     */
    map: number | Media;
    /**
     * Stand-in content. Shows a "contoh" badge on the site while placeholder badges are on (Site settings → Developer).
     */
    placeholder?: boolean | null;
  };
  cluster: {
    title: string;
    intro: string;
    /**
     * The frame sequence scrubbed by scrolling.
     */
    scene: number | Package;
    /**
     * Button that leaves an open hotspot, e.g. "Kembali ke kawasan".
     */
    backLabel: string;
    /**
     * Markers on the scene. Opening one turns the orbit to its frame and zooms in.
     */
    hotspots?:
      | {
          /**
           * List item and location title.
           */
          title: string;
          /**
           * Marker label on the image. Defaults to the title.
           */
          shortLabel?: string | null;
          /**
           * Unique id, e.g. area-plaza.
           */
          key: string;
          /**
           * Shown while the location is open.
           */
          text: string;
          /**
           * Tracked landmark the marker follows (listed on the scene package).
           */
          landmark: string;
          /**
           * Orbit angle (frame) shown when opened. A new frame also needs a sharp detail frame (README).
           */
          defaultFrame: number;
          id?: string | null;
        }[]
      | null;
  };
  fasilitas: {
    title: string;
    intro?: string | null;
    /**
     * 1–10 slides. Drag to reorder.
     */
    items: (number | Facility)[];
  };
  tipe: {
    title: string;
    intro?: string | null;
    /**
     * 1–6 types, 3 per row. Only types picked here get a page on the site.
     */
    items: (number | UnitType)[];
  };
  unitUpdate: {
    title: string;
    intro?: string | null;
    /**
     * The plan the dots sit on, at least 1600 px wide. Dots are % of this image: after replacing it, re-check every unit’s position.
     */
    siteplan: number | Media;
    /**
     * Stand-in content. Shows a "contoh" badge on the site while placeholder badges are on (Site settings → Developer).
     */
    placeholder?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Short wordmark in the header, e.g. "DR".
   */
  name: string;
  /**
   * Official name; page titles and footer.
   */
  fullName: string;
  /**
   * Optional. SVG preferred. Replaces the text wordmark in the header.
   */
  logo?: (number | null) | Media;
  /**
   * Light version for the header over the hero video. If empty, the logo above is shown in white.
   */
  logoOnDark?: (number | null) | Media;
  /**
   * Optional square icon (SVG or 512 px PNG). If empty, one is drawn from the name.
   */
  favicon?: (number | null) | Media;
  /**
   * Language of the page (for browsers and screen readers). It does not translate the text.
   */
  language: 'id' | 'en';
  seo: {
    /**
     * Default meta description.
     */
    description: string;
    /**
     * Link preview image, 1200 × 630.
     */
    shareImage?: (number | null) | Media;
  };
  nav: {
    label: string;
    section: 'kawasan' | 'peta' | 'cluster' | 'fasilitas' | 'tipe' | 'unit-update';
    id?: string | null;
  }[];
  /**
   * Legend and tooltip text for siteplan dots.
   */
  statusLabels: {
    available: string;
    reserved: string;
    sold: string;
  };
  footer?: {
    /**
     * {year} and {fullName} are filled in.
     */
    copyright?: string | null;
  };
  theme: {
    accent: string;
    available: string;
    reserved: string;
    sold: string;
  };
  dev?: {
    /**
     * Show "contoh" badges on anything marked as placeholder.
     */
    showPlaceholderBadges?: boolean | null;
    /**
     * GA4 measurement ID (G-…). Empty: no analytics.
     */
    analyticsId?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Buttons, small labels and screen-reader text used across the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "labels".
 */
export interface Label {
  id: number;
  /**
   * Top bar.
   */
  header: {
    /**
     * Screen-reader name of the logo link.
     */
    homeLink: string;
    /**
     * Screen-reader name of the section links.
     */
    navLabel: string;
    /**
     * Back link on type pages.
     */
    backToUnits: string;
  };
  /**
   * Buttons inside the scroll scenes.
   */
  scene: {
    /**
     * Screen reader.
     */
    prevLocation: string;
    /**
     * Screen reader.
     */
    nextLocation: string;
  };
  facilities: {
    /**
     * Screen reader.
     */
    listLabel: string;
    /**
     * Screen reader.
     */
    prev: string;
    /**
     * Screen reader.
     */
    next: string;
  };
  /**
   * Used on type cards, type pages and the phone bar.
   */
  specs: {
    areaUnit: string;
    /**
     * Type card.
     */
    cardLandArea: string;
    /**
     * Type card.
     */
    cardBuildingArea: string;
    /**
     * Type card.
     */
    cardBedrooms: string;
    /**
     * Type card.
     */
    cardBathrooms: string;
    /**
     * Type page, top facts.
     */
    factLandArea: string;
    /**
     * Type page, top facts.
     */
    factBuildingArea: string;
    /**
     * Type page, top facts.
     */
    factBedrooms: string;
    /**
     * Type page, top facts.
     */
    factBathrooms: string;
    /**
     * Type page, info rows.
     */
    rowLandArea: string;
    /**
     * Type page, info rows.
     */
    rowBuildingArea: string;
    /**
     * Type page, info rows.
     */
    rowFloors: string;
    /**
     * Type page, info rows.
     */
    rowBedrooms: string;
    /**
     * Type page, info rows.
     */
    rowBathrooms: string;
  };
  typePage: {
    galleryButton: string;
    vrButton: string;
    /**
     * Title bar of the gallery lightbox.
     */
    galleryTitle: string;
    /**
     * Title bar of the floor plan lightbox.
     */
    floorPlanTitle: string;
    /**
     * Title bar of the VR overlay.
     */
    vrTitle: string;
    /**
     * Under the floor plan beside the viewer.
     */
    floorPlanCaption: string;
    /**
     * Screen reader.
     */
    openFloorPlan: string;
    /**
     * Screen reader.
     */
    floorPlansLabel: string;
    /**
     * Screen reader: the part list.
     */
    partsLabel: string;
    /**
     * Screen reader: the info panel.
     */
    infoLabel: string;
    /**
     * Screen reader: the bottom bar on phones.
     */
    dockLabel: string;
    /**
     * Screen reader: the 360° viewer.
     */
    viewerLabel: string;
    /**
     * Meta description of a type page without its own SEO description.
     */
    defaultDescription: string;
  };
  turntable: {
    /**
     * Screen reader: what kind of control the viewer is.
     */
    roleDescription: string;
    /**
     * Screen reader.
     */
    rotateLeft: string;
    /**
     * Screen reader.
     */
    rotateRight: string;
    /**
     * Screen reader.
     */
    viewerHint: string;
    /**
     * Shown only if a page has more than one viewer without a WebRotate license.
     */
    licenseNotice: string;
  };
  units: {
    /**
     * Screen reader: the list of dots.
     */
    siteplanLabel: string;
  };
  /**
   * Lightbox, video and VR overlay.
   */
  overlay: {
    /**
     * Screen reader.
     */
    close: string;
    /**
     * Screen reader.
     */
    prev: string;
    /**
     * Screen reader.
     */
    next: string;
    openInNewTab: string;
  };
  /**
   * Shown on placeholder content while badges are on (Site settings → Developer).
   */
  badges: {
    sequence: string;
    map: string;
    image: string;
    data: string;
    siteplan: string;
  };
  notFound: {
    title: string;
    text: string;
    button: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        loopVideo?: T;
        cover?: T;
        fullVideo?: T;
        playLabel?: T;
        scrollCue?: T;
      };
  kawasan?:
    | T
    | {
        title?: T;
        intro?: T;
        scene?: T;
        backLabel?: T;
        hotspots?:
          | T
          | {
              title?: T;
              shortLabel?: T;
              key?: T;
              text?: T;
              landmark?: T;
              defaultFrame?: T;
              id?: T;
            };
      };
  lokasi?:
    | T
    | {
        title?: T;
        intro?: T;
        map?: T;
        placeholder?: T;
      };
  cluster?:
    | T
    | {
        title?: T;
        intro?: T;
        scene?: T;
        backLabel?: T;
        hotspots?:
          | T
          | {
              title?: T;
              shortLabel?: T;
              key?: T;
              text?: T;
              landmark?: T;
              defaultFrame?: T;
              id?: T;
            };
      };
  fasilitas?:
    | T
    | {
        title?: T;
        intro?: T;
        items?: T;
      };
  tipe?:
    | T
    | {
        title?: T;
        intro?: T;
        items?: T;
      };
  unitUpdate?:
    | T
    | {
        title?: T;
        intro?: T;
        siteplan?: T;
        placeholder?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  name?: T;
  fullName?: T;
  logo?: T;
  logoOnDark?: T;
  favicon?: T;
  language?: T;
  seo?:
    | T
    | {
        description?: T;
        shareImage?: T;
      };
  nav?:
    | T
    | {
        label?: T;
        section?: T;
        id?: T;
      };
  statusLabels?:
    | T
    | {
        available?: T;
        reserved?: T;
        sold?: T;
      };
  footer?:
    | T
    | {
        copyright?: T;
      };
  theme?:
    | T
    | {
        accent?: T;
        available?: T;
        reserved?: T;
        sold?: T;
      };
  dev?:
    | T
    | {
        showPlaceholderBadges?: T;
        analyticsId?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "labels_select".
 */
export interface LabelsSelect<T extends boolean = true> {
  header?:
    | T
    | {
        homeLink?: T;
        navLabel?: T;
        backToUnits?: T;
      };
  scene?:
    | T
    | {
        prevLocation?: T;
        nextLocation?: T;
      };
  facilities?:
    | T
    | {
        listLabel?: T;
        prev?: T;
        next?: T;
      };
  specs?:
    | T
    | {
        areaUnit?: T;
        cardLandArea?: T;
        cardBuildingArea?: T;
        cardBedrooms?: T;
        cardBathrooms?: T;
        factLandArea?: T;
        factBuildingArea?: T;
        factBedrooms?: T;
        factBathrooms?: T;
        rowLandArea?: T;
        rowBuildingArea?: T;
        rowFloors?: T;
        rowBedrooms?: T;
        rowBathrooms?: T;
      };
  typePage?:
    | T
    | {
        galleryButton?: T;
        vrButton?: T;
        galleryTitle?: T;
        floorPlanTitle?: T;
        vrTitle?: T;
        floorPlanCaption?: T;
        openFloorPlan?: T;
        floorPlansLabel?: T;
        partsLabel?: T;
        infoLabel?: T;
        dockLabel?: T;
        viewerLabel?: T;
        defaultDescription?: T;
      };
  turntable?:
    | T
    | {
        roleDescription?: T;
        rotateLeft?: T;
        rotateRight?: T;
        viewerHint?: T;
        licenseNotice?: T;
      };
  units?:
    | T
    | {
        siteplanLabel?: T;
      };
  overlay?:
    | T
    | {
        close?: T;
        prev?: T;
        next?: T;
        openInNewTab?: T;
      };
  badges?:
    | T
    | {
        sequence?: T;
        map?: T;
        image?: T;
        data?: T;
        siteplan?: T;
      };
  notFound?:
    | T
    | {
        title?: T;
        text?: T;
        button?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionExport".
 */
export interface TaskCreateCollectionExport {
  input: {
    id: string;
    name: string;
    batchSize?: number | null;
    collectionSlug: 'unit-types' | 'units' | 'facilities' | 'media' | 'packages' | 'users' | 'exports' | 'imports';
    drafts?: ('yes' | 'no') | null;
    exportCollection: string;
    fields?: string[] | null;
    format: 'csv' | 'json';
    limit?: number | null;
    locale?: string | null;
    maxLimit?: number | null;
    page?: number | null;
    sort?: string | null;
    userCollection?: string | null;
    userID?: string | null;
    where?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionImport".
 */
export interface TaskCreateCollectionImport {
  input: {
    importId: string;
    importCollection: string;
    userID?: string | null;
    userCollection?: string | null;
    batchSize?: number | null;
    debug?: boolean | null;
    defaultVersionStatus?: ('draft' | 'published') | null;
    maxLimit?: number | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}